apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- AMQ/AMQaddress.yaml
- AMQ/broker.yaml
- AMQ/svc-mqtt-loadbalancer.yaml
- Camel/camel-secret.yaml
- Camel/camelUser.yaml
- Camel/kamelet.yaml
- Camel/integration.yaml
- Kafka/ca-cert.yaml
- Kafka/kafka.yaml
- Kafka/kafka-user.yaml
- Kafka/mirrormakeUser.yaml
- Kafka/mirrormaker-secret.yaml
- Kafka/topicKafka.yaml

